repos:
-   repo: git://github.com/pre-commit/pre-commit-hooks
    rev: v1.4.0
    hooks:
    -   id: check-added-large-files
    -   id: check-merge-conflict
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-json
    -   id: check-yaml
    -   id: debug-statements
    -   id: name-tests-test
        exclude: ^tests/testing.py$
    -   id: flake8
    -   id: requirements-txt-fixer
    -   id: pretty-format-json
        args:
        - --autofix
    -   id: fix-encoding-pragma
-   repo: https://github.com/asottile/pyupgrade
    rev: v1.4.0
    hooks:
    -   id: pyupgrade
-   repo: https://github.com/ambv/black
    rev: 18.6b4
    hooks:
    - id: black
-   repo: https://github.com/asottile/reorder_python_imports
    rev: v1.1.0
    hooks:
    -   id: reorder-python-imports
        args:
        - --add-import
        - from __future__ import absolute_import
        - --add-import
        - from __future__ import unicode_literals
